// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtg9Musq70xF8eObAZM6YCTiuIWnYiNxs',
    appId: '1:1053292896141:web:85b9a24f01652141e9a7c4',
    messagingSenderId: '1053292896141',
    projectId: 'traveltrack-gemastik-app',
    authDomain: 'traveltrack-gemastik-app.firebaseapp.com',
    storageBucket: 'traveltrack-gemastik-app.firebasestorage.app',
    measurementId: 'G-TP6RQ0ECHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtH_6pO9pSCtt-w23uq59aMWoHxbhj8VA',
    appId: '1:1053292896141:android:ef50b4ad8e3f4e23e9a7c4',
    messagingSenderId: '1053292896141',
    projectId: 'traveltrack-gemastik-app',
    storageBucket: 'traveltrack-gemastik-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGi9aapu50AembbKaijWh0m6Leusp5Xc',
    appId: '1:1053292896141:ios:efcdba76be2eedd9e9a7c4',
    messagingSenderId: '1053292896141',
    projectId: 'traveltrack-gemastik-app',
    storageBucket: 'traveltrack-gemastik-app.firebasestorage.app',
    iosBundleId: 'com.example.appGemastik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGi9aapu50AembbKaijWh0m6Leusp5Xc',
    appId: '1:1053292896141:ios:efcdba76be2eedd9e9a7c4',
    messagingSenderId: '1053292896141',
    projectId: 'traveltrack-gemastik-app',
    storageBucket: 'traveltrack-gemastik-app.firebasestorage.app',
    iosBundleId: 'com.example.appGemastik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtg9Musq70xF8eObAZM6YCTiuIWnYiNxs',
    appId: '1:1053292896141:web:993eb830b4577627e9a7c4',
    messagingSenderId: '1053292896141',
    projectId: 'traveltrack-gemastik-app',
    authDomain: 'traveltrack-gemastik-app.firebaseapp.com',
    storageBucket: 'traveltrack-gemastik-app.firebasestorage.app',
    measurementId: 'G-CD7T02CXD3',
  );
}
